version: '3.4'

services:
  bot:
    container_name: bot
    build:
      context: ./bot
      target: prod
    volumes:
      - ./bot:/service
    depends_on:
      - core
    links:
      - core
    environment:
      - TGRATESBOT_TOKEN
      - TGRATESBOT_API_KEY
  
  core:
    container_name: core
    build:
      context: ./core
      target: prod
    volumes:
      - ./core:/service
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - TGRATESBOT_DB_HOST
      - TGRATESBOT_DB_PORT
      - TGRATESBOT_DB_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - TGRATESBOT_API_KEY

  rates_collector:
    container_name: rates_collector
    build:
      context: ./rates_collector
      target: prod
    volumes:
      - ./rates_collector:/service
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - TGRATESBOT_DB_HOST
      - TGRATESBOT_DB_PORT
      - TGRATESBOT_DB_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=TGRATESBOT_DB_NAME
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
